version: '3'

services:

  fks_mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=fksbank
    ports:
      - 3306:3306
    container_name: fks_mysql
    networks:
      - fks_network
    volumes:
      - fks_volume:/var/lib/mysql

  fks_rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
      - 15671:15671
    container_name: fks_rabbitmq
    networks:
      - fks_network
    volumes:
      - ./docker/rabbitmq/config:/var/lib/rabbitmq/config/generated

  fks-redis:
    image: redis
    command: redis-server --requirepass 12345
    ports:
      - 6379:6379
    container_name: fks_redis
    networks:
      - fks_network
    volumes:
      - fks_volume:/var/lib/redis
      - fks_volume:/usr/local/etc/redis/redis.conf

volumes:
  fks_volume:

networks:
  fks_network:
